#!/bin/sh
code_dir=/etc/puppet/code/production
cd "${code_dir}" || exit 1
/usr/bin/git pull
/usr/bin/puppet apply --modulepath="${code_dir}/modules:/usr/share/puppet/modules:/etc/puppet/code/production/modules" "${code_dir}/manifests/$(hostname -s).pp"
