#!/bin/sh
code_dir=/etc/puppet/code/production
cd "${code_dir}" || exit 1
/usr/bin/git pull
/usr/bin/puppet apply --modulepath="/etc/puppet/code/modules:/usr/share/puppet/modules:${code_dir}/modules" "${code_dir}/manifests/$(hostname -s).pp"
