type Irssi::Server = Struct[{
    address        => Stdlib::Fqdn,
    port           => Optional[Stdlib::Port],
    use_tls        => Optional[Boolean],
    tls_verify     => Optional[Boolean],
    tls_cert       => Optional[String[1]],
    autoconnect    => Optional[Boolean],
    username       => Optional[String[1]],
    password       => Optional[String[1]],
    kicks          => Optional[Integer[1]],
    querychans     => Optional[Integer[1]],
    msgs           => Optional[Integer[1]],
    whois          => Optional[Integer[1]],
    sasl_mechanism => Optional[String[1]],
    sasl_username  => Optional[String[1]],
    sasl_password  => Optional[String[1]],
    channels       => Optional[Hash[String[1],Irssi::Channel]],
}]
